### ISSUE TITLE
Cant Create Listing, and it might by(probably is) my fault

### ISSUE THREAD

**Issue by Adelance** [Nicklason/node-bptf-listings#6]
//This is my code and Im stuck right now. I cant figure it out how to fix it.
//When i run this chema and listings are both ready but nothing else happens.
const async = require('async');
const BptfListings = require('bptf-listings');
const Schema = require('tf2-schema');

const schemaManager = new Schema({ apiKey: 'apikey' });

const listingManager = new BptfListings({
    token: 'token',
    steamid: 'mysteamid',
    batchSize: 10
});

async.series([
    function (callback) {
        schemaManager.init(callback);
    },
    function (callback) {
        listingManager.schema = schemaManager.schema;
        listingManager.init(callback);
    }
], function (err) {
    if (err) {
        throw err;
    }

});

schemaManager.on('ready', () => {
    console.log('tf2-schema is ready!');
});
listingManager.on('ready', () => {
    console.log('bptf-listings is ready!');
});

listingManager.on('ready', () => {

    listingManager.createListing({
        id: '8859162733',
        intent: 1,
        details: 'Testing',
        buyout: false,
        currencies: {
            keys: 0,
            metal: 2
        }
    }, true);

});

listingManager.on('actions', function (actions) {
    console.log(actions);
});

**Comment by Nicklason** [comment]
It is because it expects a property called "time" on every listing you made, it is not documented or in any of the examples so I can understand the confusion.

Try this

```js
listingManager.createListing({
    id: '8859162733',
    intent: 1,
    details: 'Testing',
    buyout: false,
    currencies: {
        keys: 0,
        metal: 2
    },
    time: new Date().getTime()
}, true);
```

You need to give it the time, it uses it to make sure that if you are attempting to make a listing for the same item twice, it will only make the newest listing that you have requested to be made. Also make sure that the assetid exists, I would suggest you to try and make a buy order to test this instead of a sell order, because they are easier to make when testing.

```js
listingManager.createListing({
    sku: '5021;6'
    intent: 0,
    details: 'Testing',
    buyout: false,
    currencies: {
        keys: 0,
        metal: 2
    },
    time: new Date().getTime()
}, true);
```

It should make a buy order for Mann Co. Supply Crate Keys with the text "Testing" and the buy price of 2 refined.

I hope this helps.

**Comment by Adelance** [comment]
Okey now it works! 
Thank You very much for help.
